# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supermercado_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(371, 548)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.table_produtos = QtWidgets.QTableView(self.centralwidget)
        self.table_produtos.setGeometry(QtCore.QRect(20, 20, 331, 421))
        self.table_produtos.setTabletTracking(False)
        self.table_produtos.setObjectName("table_produtos")
        self.table_produtos.verticalHeader().setSortIndicatorShown(False)
        self.table_produtos.setRowCount(3)
        self.table_produtos.setColumnCount(3)
        self.table_produtos.setHorizontalHeaderLabels(('Produtos','Valor','Quantidade'))
        
        self.caixa_qtd = QtWidgets.QSpinBox(self.centralwidget)
        self.caixa_qtd.setGeometry(QtCore.QRect(240, 470, 41, 21))
        self.caixa_qtd.setObjectName("caixa_qtd")
        
        self.label_produto = QtWidgets.QLabel(self.centralwidget)
        self.label_produto.setGeometry(QtCore.QRect(30, 450, 49, 16))
        self.label_produto.setObjectName("label_produto")
        
        self.caixa_produto = QtWidgets.QLineEdit(self.centralwidget)
        self.caixa_produto.setGeometry(QtCore.QRect(30, 470, 113, 22))
        self.caixa_produto.setObjectName("caixa_produto")
        
        self.button_add = QtWidgets.QPushButton(self.centralwidget)
        self.button_add.setGeometry(QtCore.QRect(300, 470, 51, 24))
        self.button_add.setObjectName("button_add")
        
        self.caixa_valor = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.caixa_valor.setGeometry(QtCore.QRect(160, 470, 62, 22))
        self.caixa_valor.setObjectName("caixa_valor")
        
        self.label_qtd = QtWidgets.QLabel(self.centralwidget)
        self.label_qtd.setGeometry(QtCore.QRect(240, 450, 49, 16))
        self.label_qtd.setObjectName("label_qtd")
        
        self.label_valor = QtWidgets.QLabel(self.centralwidget)
        self.label_valor.setGeometry(QtCore.QRect(160, 450, 49, 16))
        self.label_valor.setObjectName("label_valor")
        
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 371, 22))
        self.menubar.setObjectName("menubar")
        
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_produto.setText(_translate("MainWindow", "Produto"))
        self.button_add.setText(_translate("MainWindow", "Add"))
        self.label_qtd.setText(_translate("MainWindow", "Qtd"))
        self.label_valor.setText(_translate("MainWindow", "Valor"))

    def ClickButtonAdd(self):
        produto = ui.caixa_produto.text()
        valor = ui.caixa_valor.text()
        quantidade = ui.caixa_qtd.text()
        ui.table_produtos.addItem("1232")
        print(produto, valor, quantidade)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.button_add.clicked.connect(ui.ClickButtonAdd)

    MainWindow.show()
    sys.exit(app.exec_())
