# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supermercado_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QTableWidget, QTableWidgetItem, QVBoxLayout, QHBoxLayout
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QFont

class Ui_compras(object):
    def setupUi(self, compras):
        compras.setObjectName("compras")
        compras.resize(380, 550)
        self.centralwidget = QtWidgets.QWidget(compras)
        self.centralwidget.setObjectName("centralwidget")
        
# designer adicionar       
        self.label_produto = QtWidgets.QLabel(self.centralwidget)
        self.label_produto.setGeometry(QtCore.QRect(20, 470, 49, 16))
        self.label_produto.setObjectName("label_produto")
        
        self.caixa_produto = QtWidgets.QLineEdit(self.centralwidget)
        self.caixa_produto.setGeometry(QtCore.QRect(22, 490, 121, 22))
        self.caixa_produto.setObjectName("caixa_produto")
        
        self.button_add = QtWidgets.QPushButton(self.centralwidget)
        self.button_add.setGeometry(QtCore.QRect(300, 490, 51, 24))
        self.button_add.setObjectName("button_add")
        
        self.caixa_valor = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.caixa_valor.setGeometry(QtCore.QRect(160, 490, 62, 22))
        self.caixa_valor.setObjectName("caixa_valor")
        
        self.label_valor = QtWidgets.QLabel(self.centralwidget)
        self.label_valor.setGeometry(QtCore.QRect(160, 470, 49, 16))
        self.label_valor.setObjectName("label_valor")

        self.label_qtd = QtWidgets.QLabel(self.centralwidget)
        self.label_qtd.setGeometry(QtCore.QRect(240, 470, 49, 16))
        self.label_qtd.setObjectName("label_qtd")

        self.caixa_qtd = QtWidgets.QSpinBox(self.centralwidget)
        self.caixa_qtd.setGeometry(QtCore.QRect(240, 490, 41, 21))
        self.caixa_qtd.setObjectName("caixa_qtd")
        
#designer Total das compras
        self.label_total = QtWidgets.QLabel(self.centralwidget)
        self.label_total.setGeometry(QtCore.QRect(20, 445, 49, 16))
        self.label_total.setObjectName("label_total")
        self.label_total.setFont(QFont("Arial", 12))

        self.label_vtotal = QtWidgets.QLabel(self.centralwidget)
        self.label_vtotal.setGeometry(QtCore.QRect(75, 445, 49, 16))
        self.label_vtotal.setObjectName("label_vtotal")
        self.label_vtotal.setFont(QFont("Arial", 12))
        
#designer deletar
        self.button_del = QtWidgets.QPushButton(self.centralwidget)
        self.button_del.setGeometry(QtCore.QRect(305, 415, 51, 24))
        self.button_del.setObjectName("button_del")

        self.label_descdel = QtWidgets.QLabel(self.centralwidget)
        self.label_descdel.setGeometry(QtCore.QRect(20, 410, 300, 30))
        self.label_descdel.setObjectName("label_descdel")

#Designer Table
        self.table_produtos = QtWidgets.QTableWidget(self.centralwidget)
        self.table_produtos.setGeometry(QtCore.QRect(20, 10, 335, 400))
        self.table_produtos.setObjectName("table_produtos")
        self.table_produtos.setColumnCount(3)
        self.table_produtos.setRowCount(1)
        self.table_produtos.setHorizontalHeaderLabels(('Produtos','Valor','Quantidade'))
        self.table_produtos.setColumnWidth(0, 170)
        self.table_produtos.setColumnWidth(1, 74)
        self.table_produtos.setColumnWidth(2, 70)
        
        compras.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(compras)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 371, 22))
        self.menubar.setObjectName("menubar")
        compras.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(compras)
        self.statusbar.setObjectName("statusbar")
        compras.setStatusBar(self.statusbar)

        self.retranslateUi(compras)
        QtCore.QMetaObject.connectSlotsByName(compras)

    def retranslateUi(self, compras):
        _translate = QtCore.QCoreApplication.translate
        compras.setWindowTitle(_translate("compras", "MainWindow"))
        self.label_produto.setText(_translate("compras", "Produto"))
        self.button_add.setText(_translate("compras", "Add"))
        self.button_del.setText(_translate("compras", "Delete"))
        self.label_descdel.setText(_translate("compras", "Selecione a linha clicando em cima de um dos números \na esquerda e pressione o botão delete para apagar o item"))
        self.label_total.setText(_translate("compras", "Total = "))
        self.label_vtotal.setText(_translate("compras", "00 "))
        self.label_qtd.setText(_translate("compras", "Qtd"))
        self.label_valor.setText(_translate("compras", "Valor"))

    def ClickAdd(self):
        global click
        click = click + 1
        self.table_produtos.setRowCount(click+1)
        produto = ui.caixa_produto.text()
        valor = ui.caixa_valor.text()
        quantidade = ui.caixa_qtd.text()
        self.InserirDados(click, produto, valor, quantidade)

    def InserirDados(self, x, produto, valor, quantidade):
        # Insere os dados na tabela
        self.table_produtos.setItem(x, 0, QTableWidgetItem(produto))
        self.table_produtos.setItem(x, 1, QTableWidgetItem(str(valor)))
        self.table_produtos.setItem(x, 2, QTableWidgetItem(str(quantidade)))
        self.caixa_produto.setText("")
        self.caixa_qtd.setValue(0)
        self.caixa_valor.setValue(0)
        self.calcular_total(x)

    def calcular_total(self):
        #item


    def ExcluirItem(self, x):
        selected_row = self.table_produtos.currentRow()
        if selected_row >= 0:  # Verifica se alguma linha está selecionada
            self.table_produtos.removeRow(selected_row)
        else:
            print("Nenhuma linha selecionada")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    compras = QtWidgets.QMainWindow()
    ui = Ui_compras()
    ui.setupUi(compras)
    ui.button_add.clicked.connect(ui.ClickAdd)
    ui.button_del.clicked.connect(ui.ExcluirItem)
    click = -1
    compras.show()
    sys.exit(app.exec_())
